---
- name: Install k3s cluster
  hosts: k3s_master
  become: true
  tasks:
    - name: Create .cache/tmp directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.cache/tmp"
        state: directory
        mode: '0755'

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: "{{ ansible_env.HOME }}/.cache/tmp/k3s-install.sh"
        mode: '0755'

    - name: Install k3s # noqa: command-instead-of-shell
      ansible.builtin.shell: "{{ ansible_env.HOME }}/.cache/tmp/k3s-install.sh"
      environment:
        INSTALL_K3S_EXEC: "server --config {{ playbook_dir }}/k3s/config.yaml"
      args:
        creates: /usr/local/bin/k3s

    - name: Wait for k3s to be ready
      ansible.builtin.wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        state: present
        timeout: 60
    - name: Firewalld
      block:
        - name: Check if firewalld is running
          ansible.builtin.systemd:
            name: firewalld
          register: firewalld_status
          failed_when: false

        - name: Open k3s API port in firewalld
          ansible.posix.firewalld:
            port: 6443/tcp
            permanent: true
            state: enabled
            immediate: true
          when:
            - firewalld_status.status is defined
            - firewalld_status.status.ActiveState == "active"

    - name: Fetch kubeconfig from master
      ansible.builtin.slurp:
        src: /etc/rancher/k3s/k3s.yaml
      register: kubeconfig_content

    - name: Parse kubeconfig
      ansible.builtin.set_fact:
        kubeconfig_data: "{{ kubeconfig_content.content | b64decode | from_yaml }}"

    - name: Write original to repo directory
      ansible.builtin.copy:
        content: "{{ kubeconfig_data | to_nice_yaml }}"
        dest: "{{ playbook_dir }}/original.kubeconfig"
        mode: '0644'
      delegate_to: localhost

    - name: Create external kubeconfig
      block:
        - name: Update server address in kubeconfig
          ansible.utils.update_fact:
            updates:
              - path: kubeconfig_data.clusters[0].cluster.server
                value: "https://{{ ansible_fqdn }}:6443"
              - path: kubeconfig_data.contexts[0].name
                value: "{{ ansible_hostname }}"
              - path: kubeconfig_data.current-context
                value: "{{ ansible_hostname }}"
          register: updated_kubeconfig

        - name: Write kubeconfig to repo directory
          ansible.builtin.copy:
            content: "{{ updated_kubeconfig.kubeconfig_data | to_nice_yaml }}"
            dest: "{{ playbook_dir }}/external.kubeconfig"
            mode: '0644'
          delegate_to: localhost
